# Generated by Django 4.1.7 on 2023-05-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0001_initial"),
        ("app_comments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentproduct",
            name="content",
            field=models.TextField(max_length=500, verbose_name="Отзыв"),
        ),
        migrations.AlterField(
            model_name="commentproduct",
            name="edit_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата редактирования"
            ),
        ),
        migrations.AlterField(
            model_name="commentproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="app_products.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="commentproduct",
            name="pub_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
    ]
